name: hello
version: 0.1.0
extra-source-files:
  - README.md

dependencies:
  - base
  - optparse-generic

default-extensions:
  - OverloadedStrings

library:
  exposed-modules:
    - Hello
  source-dirs: src

executables:
  hello:
    main: app/Main.hs
    dependencies:
      - hello

tests:
  test:
    main: test.hs
    source-dirs: test
    dependencies:
      - hello
      - tasty
      - tasty-discover
      - tasty-hspec
      - tasty-hedgehog
      - hedgehog
      - hspec

benchmarks:
  bench:
    main: bench.hs
    source-dirs: bench
    dependencies:
      - hello
      - tasty-bench
    ghc-options: -O2
